import { SkillItem } from '@/types/calculator.types';

// Crafting items organized by category
export const CRAFTING_ITEMS: SkillItem[] = [
    // Leather gear
    {
        name: 'Leather Trousers',
        level: 1,
        exp: 30,
        seconds: 7.5,
        expPerSecond: 4.0,
        goldValue: 40,
        goldPerSecond: 5.33,
        category: 'Leather gear',
    },
    {
        name: 'Leather Coat',
        level: 1,
        exp: 35,
        seconds: 7.5,
        expPerSecond: 4.67,
        goldValue: 55,
        goldPerSecond: 7.33,
        category: 'Leather gear',
    },
    {
        name: 'Orange Trousers',
        level: 20,
        exp: 55,
        seconds: 7.5,
        expPerSecond: 7.33,
        goldValue: 150,
        goldPerSecond: 20.0,
        category: 'Leather gear',
    },
    {
        name: 'Orange Coat',
        level: 20,
        exp: 65,
        seconds: 7.5,
        expPerSecond: 8.67,
        goldValue: 175,
        goldPerSecond: 23.33,
        category: 'Leather gear',
    },
    {
        name: 'Green Trousers',
        level: 40,
        exp: 85,
        seconds: 7.5,
        expPerSecond: 11.33,
        goldValue: 250,
        goldPerSecond: 33.33,
        category: 'Leather gear',
    },
    {
        name: 'Green Coat',
        level: 40,
        exp: 100,
        seconds: 7.5,
        expPerSecond: 13.33,
        goldValue: 275,
        goldPerSecond: 36.67,
        category: 'Leather gear',
    },
    {
        name: 'Red Trousers',
        level: 60,
        exp: 110,
        seconds: 7.5,
        expPerSecond: 14.67,
        goldValue: 350,
        goldPerSecond: 46.67,
        category: 'Leather gear',
    },
    {
        name: 'Red Coat',
        level: 60,
        exp: 125,
        seconds: 7.5,
        expPerSecond: 16.67,
        goldValue: 375,
        goldPerSecond: 50.0,
        category: 'Leather gear',
    },
    {
        name: 'Black Trousers',
        level: 80,
        exp: 150,
        seconds: 7.5,
        expPerSecond: 20.0,
        goldValue: 500,
        goldPerSecond: 66.67,
        category: 'Leather gear',
    },
    {
        name: 'Black Coat',
        level: 80,
        exp: 185,
        seconds: 7.5,
        expPerSecond: 24.67,
        goldValue: 600,
        goldPerSecond: 80.0,
        category: 'Leather gear',
    },
    {
        name: 'Basilisk Scale Trausers',
        level: 85,
        exp: 500,
        seconds: 6,
        expPerSecond: 83.33,
        goldValue: 25000,
        goldPerSecond: 4166.67,
        category: 'Leather gear',
    },
    {
        name: 'Basilisk Scale Coat',
        level: 85,
        exp: 500,
        seconds: 6,
        expPerSecond: 83.33,
        goldValue: 25000,
        goldPerSecond: 4166.67,
        category: 'Leather gear',
    },
    {
        name: 'Astronomical Leather Trausers',
        level: 95,
        exp: 1000,
        seconds: 7.5,
        expPerSecond: 133.33,
        goldValue: 80000,
        goldPerSecond: 3333.33,
        category: 'Leather gear',
    },
    {
        name: 'Astronomical Leather Coat',
        level: 95,
        exp: 1000,
        seconds: 7.5,
        expPerSecond: 133.33,
        goldValue: 80000,
        goldPerSecond: 3333.33,
        category: 'Leather gear',
    },

    // Ammunition
    {
        name: 'Bronze Arrow',
        level: 1,
        exp: 20,
        seconds: 6,
        expPerSecond: 3.33,
        goldValue: 60,
        goldPerSecond: 10.0,
        category: 'Ammunition',
    },
    {
        name: 'Iron Arrow',
        level: 10,
        exp: 25,
        seconds: 6,
        expPerSecond: 4.17,
        goldValue: 90,
        goldPerSecond: 15.0,
        category: 'Ammunition',
    },
    {
        name: 'Steel Arrow',
        level: 20,
        exp: 30,
        seconds: 6,
        expPerSecond: 5.0,
        goldValue: 150,
        goldPerSecond: 25.0,
        category: 'Ammunition',
    },
    {
        name: 'Platinum Arrow',
        level: 40,
        exp: 35,
        seconds: 6,
        expPerSecond: 5.83,
        goldValue: 250,
        goldPerSecond: 41.67,
        category: 'Ammunition',
    },
    {
        name: 'Meteorite Arrow',
        level: 60,
        exp: 40,
        seconds: 6,
        expPerSecond: 6.67,
        goldValue: 350,
        goldPerSecond: 58.33,
        category: 'Ammunition',
    },
    {
        name: 'Titanium Arrow',
        level: 70,
        exp: 50,
        seconds: 6,
        expPerSecond: 8.33,
        goldValue: 500,
        goldPerSecond: 83.33,
        category: 'Ammunition',
    },
    {
        name: 'Astronomical Arrow',
        level: 80,
        exp: 80,
        seconds: 6,
        expPerSecond: 13.33,
        goldValue: 80000,
        goldPerSecond: 13333.33,
        category: 'Ammunition',
    },

    // Fabric
    {
        name: 'Magical Robe',
        level: 20,
        exp: 55,
        seconds: 7.5,
        expPerSecond: 7.33,
        goldValue: 40,
        goldPerSecond: 5.33,
        category: 'Fabric',
    },
    {
        name: 'Magical Trousers',
        level: 20,
        exp: 48,
        seconds: 7.5,
        expPerSecond: 6.4,
        goldValue: 30,
        goldPerSecond: 4.0,
        category: 'Fabric',
    },
    {
        name: 'Enchanted Robe',
        level: 40,
        exp: 70,
        seconds: 7.5,
        expPerSecond: 9.33,
        goldValue: 95,
        goldPerSecond: 12.67,
        category: 'Fabric',
    },
    {
        name: 'Enchanted Trousers',
        level: 40,
        exp: 65,
        seconds: 7.5,
        expPerSecond: 8.67,
        goldValue: 80,
        goldPerSecond: 10.67,
        category: 'Fabric',
    },
    {
        name: 'Cursed Robe',
        level: 70,
        exp: 125,
        seconds: 7.5,
        expPerSecond: 16.67,
        goldValue: 200,
        goldPerSecond: 26.67,
        category: 'Fabric',
    },
    {
        name: 'Cursed Trousers',
        level: 70,
        exp: 110,
        seconds: 7.5,
        expPerSecond: 14.67,
        goldValue: 150,
        goldPerSecond: 21.33,
        category: 'Fabric',
    },

    // Refinement
    {
        name: 'Refined (T1) Gem',
        level: 10,
        exp: 1000,
        seconds: 1,
        expPerSecond: 1000.0,
        goldValue: 7500,
        goldPerSecond: 7500.0,
        category: 'Refinement',
    },
    {
        name: 'Great (T2) Gem',
        level: 25,
        exp: 2000,
        seconds: 1,
        expPerSecond: 2000.0,
        goldValue: 15000,
        goldPerSecond: 15000.0,
        category: 'Refinement',
    },
    {
        name: 'Elite (T3) Gem',
        level: 40,
        exp: 5000,
        seconds: 1,
        expPerSecond: 5000.0,
        goldValue: 35000,
        goldPerSecond: 35000.0,
        category: 'Refinement',
    },
    {
        name: 'Superior (T4) Gem',
        level: 50,
        exp: 10000,
        seconds: 1,
        expPerSecond: 10000.0,
        goldValue: 80000,
        goldPerSecond: 80000.0,
        category: 'Refinement',
    },
    {
        name: 'Outstanding (T5) Gem',
        level: 70,
        exp: 25000,
        seconds: 1,
        expPerSecond: 25000.0,
        goldValue: 175000,
        goldPerSecond: 175000.0,
        category: 'Refinement',
    },
    {
        name: 'Godlike (T6) Gem',
        level: 85,
        exp: 50000,
        seconds: 1,
        expPerSecond: 50000.0,
        goldValue: 350000,
        goldPerSecond: 350000.0,
        category: 'Refinement',
    },
    {
        name: 'Otherworldly (T7) Gem',
        level: 105,
        exp: 200000,
        seconds: 1,
        expPerSecond: 200000.0,
        goldValue: 1150000,
        goldPerSecond: 1150000.0,
        category: 'Refinement',
    },
];

// Map of skills to their items
export const SKILL_ITEMS_MAP: Record<string, SkillItem[]> = {
    crafting: CRAFTING_ITEMS,
    // Add other skills as they are implemented
};
