import { SkillItem } from '@/types/calculator.types';

// Extended interface for fishing items
interface FishingItem extends SkillItem {
    cookingExp: number;
}

export const FISHING_ITEMS: FishingItem[] = [
    {
        name: 'Piranha',
        level: 1,
        exp: 11.25,
        seconds: 5.25,
        expPerSecond: 2.14,
        goldValue: 5,
        goldPerSecond: 1.0,
        cookingExp: 10,
    },
    {
        name: 'Perch',
        level: 10,
        exp: 18.75,
        seconds: 7.5,
        expPerSecond: 2.5,
        goldValue: 8,
        goldPerSecond: 1.1,
        cookingExp: 16,
    },
    {
        name: 'Mackerel',
        level: 15,
        exp: 23.25,
        seconds: 9,
        expPerSecond: 2.58,
        goldValue: 10,
        goldPerSecond: 1.1,
        cookingExp: 20,
    },
    {
        name: 'Cod',
        level: 20,
        exp: 35.25,
        seconds: 12,
        expPerSecond: 2.94,
        goldValue: 14,
        goldPerSecond: 1.2,
        cookingExp: 26,
    },
    {
        name: 'Trout',
        level: 25,
        exp: 29,
        seconds: 9,
        expPerSecond: 3.22,
        goldValue: 16,
        goldPerSecond: 1.8,
        cookingExp: 33,
    },
    {
        name: 'Salmon',
        level: 30,
        exp: 45,
        seconds: 13.5,
        expPerSecond: 3.33,
        goldValue: 17,
        goldPerSecond: 1.3,
        cookingExp: 40,
    },
    {
        name: 'Carp',
        level: 40,
        exp: 33,
        seconds: 9.5,
        expPerSecond: 3.47,
        goldValue: 18,
        goldPerSecond: 1.9,
        cookingExp: 55,
    },
    {
        name: 'Zander',
        level: 50,
        exp: 54,
        seconds: 15,
        expPerSecond: 3.6,
        goldValue: 23,
        goldPerSecond: 1.5,
        cookingExp: 80,
    },
    {
        name: 'Pufferfish',
        level: 60,
        exp: 69,
        seconds: 18.75,
        expPerSecond: 3.68,
        goldValue: 30,
        goldPerSecond: 1.6,
        cookingExp: 105,
    },
    {
        name: 'Anglerfish',
        level: 80,
        exp: 123,
        seconds: 30,
        expPerSecond: 4.1,
        goldValue: 50,
        goldPerSecond: 1.7,
        cookingExp: 155,
    },
    {
        name: 'Tuna',
        level: 90,
        exp: 205,
        seconds: 45,
        expPerSecond: 4.56,
        goldValue: 65,
        goldPerSecond: 1.4,
        cookingExp: 255,
    },
    {
        name: 'Bloodmoon eel',
        level: 100,
        exp: 610,
        seconds: 90,
        expPerSecond: 6.78,
        goldValue: 40,
        goldPerSecond: 0.5,
        cookingExp: 892,
    },
];
