// This hurt my soul

const items: { [key: number]: string } = {
    0: 'Spruce Log',
    1: 'Pine Log',
    2: 'Chestnut Log',
    3: 'Raw Roach',
    4: 'Raw Perch',
    5: 'Raw Pike',
    6: 'Oak Log',
    7: 'Maple Log',
    8: 'Teak Log',
    9: 'Mahogany Log',
    10: 'Yew Log',
    11: 'Raw Shrimp',
    12: 'Raw Mackerel',
    13: 'Raw Trout',
    14: 'Raw Salmon',
    15: 'Raw Carp',
    16: 'Raw Bass',
    17: 'Raw Lobster',
    18: 'Raw Shark',
    19: 'Gold',
    20: 'Spruce Plank',
    21: 'Pine Plank',
    22: 'Chestnut Plank',
    23: 'Oak Plank',
    24: 'Maple Plank',
    25: 'Teak Plank',
    26: 'Mahogany Plank',
    27: 'Yew Plank',
    28: 'Tin Ore',
    29: 'Copper Ore',
    30: 'Iron Ore',
    31: 'Coal Ore',
    32: 'Silver Ore',
    33: 'Gold Ore',
    34: 'Bronze Bar',
    35: 'Iron Bar',
    36: 'Steel Bar',
    37: 'Silver Bar',
    38: 'Gold Bar',
    39: 'Platinum Ore',
    40: 'Adamantite Ore',
    41: 'Meteorite Ore',
    42: 'Titanium Ore',
    43: 'Platinum Bar',
    44: 'Adamantite Bar',
    45: 'Meteorite Bar',
    46: 'Titanium Bar',
    47: 'Astronomical Ore',
    48: 'Astronomical Bar',
    49: 'Bronze Platebody',
    50: 'Bronze Platelegs',
    51: 'Bronze Helmet',
    52: 'Bronze Shield',
    53: 'Normal Pickaxe',
    54: 'Normal Hatchet',
    55: 'Iron Platebody',
    56: 'Iron Platelegs',
    57: 'Iron Helmet',
    58: 'Iron Shield',
    59: 'Refined Pickaxe',
    60: 'Refined Hatchet',
    61: 'Steel Platebody',
    62: 'Steel Platelegs',
    63: 'Steel Helmet',
    64: 'Steel Shield',
    65: 'Great Pickaxe',
    66: 'Great Hatchet',
    67: 'Silver Ring',
    68: 'Silver Amulet',
    69: 'Silver Bracelet',
    70: 'Silver Earrings',
    71: 'Gold Ring',
    72: 'Gold Amulet',
    73: 'Gold Bracelet',
    74: 'Gold Earrings',
    75: 'Platinum Platebody',
    76: 'Platinum Platelegs',
    77: 'Platinum Helmet',
    78: 'Platinum Shield',
    79: 'Elite Pickaxe',
    80: 'Elite Hatchet',
    81: 'Meteorite Platebody',
    82: 'Meteorite Platelegs',
    83: 'Meteorite Shield',
    84: 'Meteorite Helmet',
    85: 'Superior Pickaxe',
    86: 'Superior Hatchet',
    87: 'Titanium Platebody',
    88: 'Titanium Platelegs',
    89: 'Titanium Helmet',
    90: 'Titanium Shield',
    91: 'Outstanding Pickaxe',
    92: 'Outstanding Hatchet',
    93: 'Astronomical Platebody',
    94: 'Astronomical Platelegs',
    95: 'Astronomical Helmet',
    96: 'Astronomical Shield',
    97: 'Godlike Pickaxe',
    98: 'Godlike Hatchet',
    99: 'Cooked Shrimp',
    100: 'Cooked Mackerel',
    101: 'Cooked Roach',
    102: 'Cooked Perch',
    103: 'Cooked Pike',
    104: 'Cooked Trout',
    105: 'Cooked Salmon',
    106: 'Cooked Carp',
    107: 'Cooked Bass',
    108: 'Cooked Lobster',
    109: 'Cooked Shark',
    110: 'Raw Meat',
    111: 'Raw Giant Meat',
    112: 'Raw Quality Meat',
    113: 'Raw Superior Meat',
    114: 'Cooked Meat',
    115: 'Cooked Giant Meat',
    116: 'Cooked Quality Meat',
    117: 'Cooked Superior Meat',
    118: 'Nettle',
    119: 'Blackberry',
    120: 'Garlic',
    121: 'Sweet Chestnut',
    122: 'Blueberry',
    123: 'Chanterelle',
    124: 'Sea Buckthorn',
    125: 'Porcini',
    126: 'Potato Seed',
    127: 'Carrot Seed',
    128: 'Tomato Seed',
    129: 'Cabbage Seed',
    130: 'Strawberry Seed',
    131: 'Watermelon Seed',
    132: 'Potato',
    133: 'Carrot',
    134: 'Tomato',
    135: 'Cabbage',
    136: 'Strawberry',
    137: 'Watermelon',
    138: 'Onion',
    139: 'Onion Seed',
    140: 'Potato Soup',
    141: 'Meat Burger',
    142: 'Blackberry Muffin',
    143: 'Cod Soup',
    144: 'Blueberry Pie',
    145: 'Salmon Salad',
    146: 'Porcini Soup',
    147: 'Grilled Lobster',
    148: 'Power Pizza',
    149: 'Normal Longsword',
    150: 'Normal Scimitar',
    151: 'Normal Heavy Hammer',
    152: 'Normal Club',
    153: 'Normal Battle Axe',
    154: 'Normal Spear',
    155: 'Raw Anglerfish',
    156: 'Cooked Anglerfish',
    157: 'Raw Zander',
    158: 'Cooked Zander',
    159: 'Raw Piranha',
    160: 'Cooked Piranha',
    161: 'Raw Pufferfish',
    162: 'Cooked Pufferfish',
    163: 'Raw Cod',
    164: 'Cooked Cod',
    165: 'Kiwi',
    166: 'Mango',
    167: 'Pomegranate',
    168: 'Normal Bow',
    169: 'Normal Crossbow',
    170: 'Refined Longsword',
    171: 'Refined Scimitar',
    172: 'Refined Heavy Hammer',
    173: 'Refined Club',
    174: 'Refined Battle Axe',
    175: 'Refined Spear',
    176: 'Great Longsword',
    177: 'Great Scimitar',
    178: 'Great Heavy Hammer',
    179: 'Great Club',
    180: 'Great Battle Axe',
    181: 'Great Spear',
    182: 'Elite Longsword',
    183: 'Elite Scimitar',
    184: 'Elite Heavy Hammer',
    185: 'Elite Club',
    186: 'Elite Battle Axe',
    187: 'Elite Spear',
    188: 'Superior Longsword',
    189: 'Superior Scimitar',
    190: 'Superior Heavy Hammer',
    191: 'Superior Club',
    192: 'Superior Battle Axe',
    193: 'Superior Spear',
    194: 'Outstanding Longsword',
    195: 'Outstanding Scimitar',
    196: 'Outstanding Heavy Hammer',
    197: 'Outstanding Club',
    198: 'Outstanding Battle Axe',
    199: 'Outstanding Spear',
    200: 'Godlike Longsword',
    201: 'Godlike Scimitar',
    202: 'Godlike Heavy Hammer',
    203: 'Godlike Club',
    204: 'Godlike Battle Axe',
    205: 'Godlike Spear',
    206: 'Refined Bow',
    207: 'Refined Crossbow',
    208: 'Great Bow',
    209: 'Great Crossbow',
    210: 'Elite Bow',
    211: 'Elite Crossbow',
    212: 'Superior Bow',
    213: 'Superior Crossbow',
    214: 'Outstanding Bow',
    215: 'Outstanding Crossbow',
    216: 'Godlike Bow',
    217: 'Godlike Crossbow',
    218: 'Normal Staff',
    219: 'Refined Staff',
    220: 'Great Staff',
    221: 'Elite Staff',
    222: 'Superior Staff',
    223: 'Outstanding Staff',
    224: 'Godlike Staff',
    225: 'Refined Gemstone',
    226: 'Great Gemstone',
    227: 'Elite Gemstone',
    228: 'Superior Gemstone',
    229: 'Outstanding Gemstone',
    230: 'Godlike Gemstone',
    231: 'Bronze Boots',
    232: 'Iron Boots',
    233: 'Steel Boots',
    234: 'Platinum Boots',
    235: 'Meteorite Boots',
    236: 'Titanium Boots',
    237: 'Astronomical Boots',
    238: 'Bronze Gloves',
    239: 'Iron Gloves',
    240: 'Steel Gloves',
    241: 'Platinum Gloves',
    242: 'Meteorite Gloves',
    243: 'Titanium Gloves',
    244: 'Astronomical Gloves',
    245: 'Leather',
    246: 'Orange Leather',
    247: 'Green Leather',
    248: 'Red Leather',
    249: 'Black Leather',
    250: 'Orange Leather Trousers',
    251: 'Orange Leather Coat',
    252: 'Green Leather Trousers',
    253: 'Green Leather Coat',
    254: 'Red Leather Trousers',
    255: 'Red Leather Coat',
    256: 'Black Leather Trousers',
    257: 'Black Leather Coat',
    258: 'Leather Trousers',
    259: 'Leather Coat',
    260: 'Bronze Arrow',
    261: 'Iron Arrow',
    262: 'Steel Arrow',
    263: 'Platinum Arrow',
    264: 'Meteorite Arrow',
    265: 'Titanium Arrow',
    266: 'Astronomical Arrow',
    267: 'Griffin Key',
    268: 'Devil Key',
    269: 'Hades Key',
    270: 'Zeus Key',
    271: 'Medusa Key',
    272: 'Chimera Key',
    273: 'Magical Flax',
    274: 'Enchanted Flax',
    275: 'Cursed Flax',
    276: 'Magical Robe',
    277: 'Magical Trousers',
    278: 'Enchanted Robe',
    279: 'Enchanted Trousers',
    280: 'Cursed Robe',
    281: 'Cursed Trousers',
    282: 'Wizards Hat',
    283: 'Dark Mages Hat',
    284: 'Normal Fishing Rod',
    285: 'Normal Rake',
    286: 'Normal Secateurs',
    287: 'Normal Hammer',
    288: 'Normal Saw',
    289: 'Normal Cooking Pan',
    290: 'Normal Crafting Needle',
    291: 'Refined Fishing Rod',
    292: 'Refined Rake',
    293: 'Refined Secateurs',
    294: 'Refined Hammer',
    295: 'Refined Saw',
    296: 'Refined Cooking Pan',
    297: 'Refined Crafting Needle',
    298: 'Great Fishing Rod',
    299: 'Great Rake',
    300: 'Great Secateurs',
    301: 'Great Hammer',
    302: 'Great Saw',
    303: 'Great Cooking Pan',
    304: 'Great Crafting Needle',
    305: 'Elite Fishing Rod',
    306: 'Elite Rake',
    307: 'Elite Secateurs',
    308: 'Elite Hammer',
    309: 'Elite Saw',
    310: 'Elite Cooking Pan',
    311: 'Elite Crafting Needle',
    312: 'Superior Fishing Rod',
    313: 'Superior Rake',
    314: 'Superior Secateurs',
    315: 'Superior Hammer',
    316: 'Superior Saw',
    317: 'Superior Cooking Pan',
    318: 'Superior Crafting Needle',
    319: 'Outstanding Fishing Rod',
    320: 'Outstanding Rake',
    321: 'Outstanding Secateurs',
    322: 'Outstanding Hammer',
    323: 'Outstanding Saw',
    324: 'Outstanding Cooking Pan',
    325: 'Outstanding Crafting Needle',
    326: 'Godlike Fishing Rod',
    327: 'Godlike Rake',
    328: 'Godlike Secateurs',
    329: 'Godlike Hammer',
    330: 'Godlike Saw',
    331: 'Godlike Cooking Pan',
    332: 'Godlike Crafting Needle',
    333: 'Cape',
    334: 'Knights Cape',
    335: 'Royal Cape',
    336: 'Premium One Month',
    337: 'Premium Permanent',
    338: 'Effect Scimitar',
    339: 'Effect Longsword',
    340: 'Effect Club',
    341: 'Effect Battle Axe',
    342: 'Effect Heavy Hammer',
    343: 'Effect Bow',
    344: 'Effect Crossbow',
    345: 'Effect Staff',
    346: 'Effect Spear',
    347: 'Common Scroll Of Woodcutting',
    348: 'Common Scroll Of Plundering',
    349: 'Common Scroll Of Fishing',
    350: 'Common Scroll Of Mining',
    351: 'Common Scroll Of Smithing',
    352: 'Common Scroll Of Foraging',
    353: 'Common Scroll Of Farming',
    354: 'Common Scroll Of Agility',
    355: 'Common Scroll Of Crafting',
    356: 'Rare Scroll Of Woodcutting',
    357: 'Rare Scroll Of Plundering',
    358: 'Rare Scroll Of Fishing',
    359: 'Rare Scroll Of Mining',
    360: 'Rare Scroll Of Smithing',
    361: 'Rare Scroll Of Foraging',
    362: 'Rare Scroll Of Farming',
    363: 'Rare Scroll Of Agility',
    364: 'Rare Scroll Of Crafting',
    365: 'Exceptional Scroll Of Woodcutting',
    366: 'Exceptional Scroll Of Plundering',
    367: 'Exceptional Scroll Of Fishing',
    368: 'Exceptional Scroll Of Mining',
    369: 'Exceptional Scroll Of Smithing',
    370: 'Exceptional Scroll Of Foraging',
    371: 'Exceptional Scroll Of Farming',
    372: 'Exceptional Scroll Of Agility',
    373: 'Exceptional Scroll Of Crafting',
    374: 'Diamond Ring',
    375: 'Diamond Amulet',
    376: 'Diamond Bracelet',
    377: 'Diamond Earrings',
    378: 'Diamond Ore',
    379: 'Diamond Bar',
    380: 'Exceptional Scroll Of Rigour',
    381: 'Common Chest',
    382: 'Rare Chest',
    383: 'Exceptional Chest',
    384: 'Boots Of Quickness',
    385: 'Archery Boots',
    386: 'Cowboy Hat',
    387: 'Archers Hat',
    388: 'Wizards Boots',
    389: 'Wand Of Lifesteal',
    390: 'Decayed Book',
    391: 'Wizards Book',
    392: 'Book Of Terrors',
    393: 'Novices Wand',
    394: 'Archers Shield',
    395: 'Cosmetic Effect Flaming',
    396: 'Cosmetic Effect Ghostly',
    397: 'Cosmetic Effect Void',
    398: 'Cosmetic Effect Nature',
    399: 'Seaweed',
    400: 'Grape Seed',
    401: 'Grapes',
    402: 'Papaya Seed',
    403: 'Papaya',
    404: 'Dragonfruit Seed',
    405: 'Dragonfruit',
    406: 'Redwood Log',
    407: 'Magical Log',
    408: 'Potion Of Swiftness',
    409: 'Potion Of Negotiation',
    410: 'Potion Of Resurrection',
    411: 'Potion Of Forgery',
    412: 'Potion Of Great Sight',
    413: 'Potion Of Trickery',
    414: 'Potion Of Dark Magic',
    415: 'Potion Of Pure Power',
    416: 'Potion Of Ancient Knowledge',
    417: 'Silver Ring Enchanted',
    418: 'Silver Amulet Enchanted',
    419: 'Silver Bracelet Enchanted',
    420: 'Silver Earrings Enchanted',
    421: 'Gold Ring Enchanted',
    422: 'Gold Amulet Enchanted',
    423: 'Gold Bracelet Enchanted',
    424: 'Gold Earrings Enchanted',
    425: 'Diamond Ring Enchanted',
    426: 'Diamond Amulet Enchanted',
    427: 'Diamond Bracelet Enchanted',
    428: 'Diamond Earrings Enchanted',
    429: 'Common Scroll Of Rigour',
    430: 'Rare Scroll Of Rigour',
    431: 'Common Scroll Of Strength',
    432: 'Common Scroll Of Defence',
    433: 'Common Scroll Of Magic',
    434: 'Common Scroll Of Archery',
    435: 'Common Scroll Of Carpentry',
    436: 'Common Scroll Of Enchanting',
    437: 'Common Scroll Of Brewing',
    438: 'Rare Scroll Of Strength',
    439: 'Rare Scroll Of Defence',
    440: 'Rare Scroll Of Magic',
    441: 'Rare Scroll Of Archery',
    442: 'Rare Scroll Of Carpentry',
    443: 'Rare Scroll Of Enchanting',
    444: 'Rare Scroll Of Brewing',
    445: 'Exceptional Scroll Of Strength',
    446: 'Exceptional Scroll Of Defence',
    447: 'Exceptional Scroll Of Magic',
    448: 'Exceptional Scroll Of Archery',
    449: 'Exceptional Scroll Of Carpentry',
    450: 'Exceptional Scroll Of Enchanting',
    451: 'Exceptional Scroll Of Brewing',
    452: 'Null',
    453: 'Agility Cape Tier 1',
    454: 'Archery Cape Tier 1',
    455: 'Brewing Cape Tier 1',
    456: 'Carpentry Cape Tier 1',
    457: 'Cooking Cape Tier 1',
    458: 'Crafting Cape Tier 1',
    459: 'Defence Cape Tier 1',
    460: 'Enchanting Cape Tier 1',
    461: 'Farming Cape Tier 1',
    462: 'Fishing Cape Tier 1',
    463: 'Foraging Cape Tier 1',
    464: 'Health Cape Tier 1',
    465: 'Magic Cape Tier 1',
    466: 'Mining Cape Tier 1',
    467: 'Plundering Cape Tier 1',
    468: 'Rigour Cape Tier 1',
    469: 'Smithing Cape Tier 1',
    470: 'Strength Cape Tier 1',
    471: 'Woodcutting Cape Tier 1',
    472: 'Agility Cape Tier 2',
    473: 'Archery Cape Tier 2',
    474: 'Brewing Cape Tier 2',
    475: 'Carpentry Cape Tier 2',
    476: 'Cooking Cape Tier 2',
    477: 'Crafting Cape Tier 2',
    478: 'Defence Cape Tier 2',
    479: 'Enchanting Cape Tier 2',
    480: 'Farming Cape Tier 2',
    481: 'Fishing Cape Tier 2',
    482: 'Foraging Cape Tier 2',
    483: 'Health Cape Tier 2',
    484: 'Magic Cape Tier 2',
    485: 'Mining Cape Tier 2',
    486: 'Plundering Cape Tier 2',
    487: 'Rigour Cape Tier 2',
    488: 'Smithing Cape Tier 2',
    489: 'Strength Cape Tier 2',
    490: 'Woodcutting Cape Tier 2',
    491: 'Agility Cape Tier 3',
    492: 'Archery Cape Tier 3',
    493: 'Brewing Cape Tier 3',
    494: 'Carpentry Cape Tier 3',
    495: 'Cooking Cape Tier 3',
    496: 'Crafting Cape Tier 3',
    497: 'Defence Cape Tier 3',
    498: 'Enchanting Cape Tier 3',
    499: 'Farming Cape Tier 3',
    500: 'Fishing Cape Tier 3',
    501: 'Foraging Cape Tier 3',
    502: 'Health Cape Tier 3',
    503: 'Magic Cape Tier 3',
    504: 'Mining Cape Tier 3',
    505: 'Plundering Cape Tier 3',
    506: 'Rigour Cape Tier 3',
    507: 'Smithing Cape Tier 3',
    508: 'Strength Cape Tier 3',
    509: 'Woodcutting Cape Tier 3',
    510: 'Agility Cape Tier 4',
    511: 'Archery Cape Tier 4',
    512: 'Brewing Cape Tier 4',
    513: 'Carpentry Cape Tier 4',
    514: 'Cooking Cape Tier 4',
    515: 'Crafting Cape Tier 4',
    516: 'Defence Cape Tier 4',
    517: 'Enchanting Cape Tier 4',
    518: 'Farming Cape Tier 4',
    519: 'Fishing Cape Tier 4',
    520: 'Foraging Cape Tier 4',
    521: 'Health Cape Tier 4',
    522: 'Magic Cape Tier 4',
    523: 'Mining Cape Tier 4',
    524: 'Plundering Cape Tier 4',
    525: 'Rigour Cape Tier 4',
    526: 'Smithing Cape Tier 4',
    527: 'Strength Cape Tier 4',
    528: 'Woodcutting Cape Tier 4',
    529: 'Completionist Cape Tier 1',
    530: 'Completionist Cape Tier 2',
    531: 'Completionist Cape Tier 3',
    532: 'Completionist Cape Tier 4',
    533: 'Normal Lockpicks',
    534: 'Refined Lockpicks',
    535: 'Great Lockpicks',
    536: 'Elite Lockpicks',
    537: 'Superior Lockpicks',
    538: 'Outstanding Lockpicks',
    539: 'Godlike Lockpicks',
    540: 'Normal Philosopher Stone',
    541: 'Refined Philosopher Stone',
    542: 'Great Philosopher Stone',
    543: 'Elite Philosopher Stone',
    544: 'Superior Philosopher Stone',
    545: 'Outstanding Philosopher Stone',
    546: 'Godlike Philosopher Stone',
    547: 'Common Scroll Of Cooking',
    548: 'Rare Scroll Of Cooking',
    549: 'Exceptional Scroll Of Cooking',
    550: 'Boss Hunter Consumable',
    551: 'Premium Permanent Untradeable',
    552: 'Normal Jumping Rope',
    553: 'Refined Jumping Rope',
    554: 'Great Jumping Rope',
    555: 'Elite Jumping Rope',
    556: 'Superior Jumping Rope',
    557: 'Outstanding Jumping Rope',
    558: 'Godlike Jumping Rope',
    559: 'Stew',
    560: 'Toolbelt',
    561: 'Raw Tuna',
    562: 'Cooked Tuna',
    563: 'Bulwark Shield',
    564: 'Warriors Helmet',
    565: 'Divine Buckler',
    566: 'Dragon Slayers Crossbow',
    567: 'Astaroths Scimitar',
    568: 'Astronomical Flax',
    569: 'Astronomical Leather',
    570: 'Warriors Toolbelt',
    571: 'Archers Toolbelt',
    572: 'Mages Toolbelt',
    573: 'Gatherers Handbook',
    574: 'Eagleclaw Battle Axe',
    575: 'Infernal Club',
    576: 'Stygian Longsword',
    577: 'Thunderbolt Bow',
    578: 'Viperstrike Scimitar',
    579: 'Divine Staff',
    580: 'Sorcerers Staff',
    581: 'Astronomical Robe',
    582: 'Astronomical Trousers',
    583: 'Astronomical Leather Coat',
    584: 'Astronomical Leather Trousers',
    585: 'Prestige',
    586: 'Redwood Plank',
    587: 'Magical Plank',
    588: 'Lumberjacks Hat',
    589: 'Lumberjacks Shirt',
    590: 'Lumberjacks Pants',
    591: 'Miners Helmet',
    592: 'Miners Jacket',
    593: 'Miners Pants',
    594: 'Fishermans Hat',
    595: 'Fishermans Jacket',
    596: 'Fishermans Pants',
    597: 'Foragers Hat',
    598: 'Foragers Jacket',
    599: 'Foragers Shorts',
    600: 'Inventory Space Token',
    601: 'Common Fishing Bait',
    602: 'Rare Fishing Bait',
    603: 'Common Resin',
    604: 'Rare Resin',
    605: 'Common Gem Dust',
    606: 'Rare Gem Dust',
    607: 'Common Flax Essence',
    608: 'Rare Flax Essence',
    609: 'Common Compost',
    610: 'Rare Compost',
    611: 'Common Vial',
    612: 'Rare Vial',
    613: 'Centaurs Shield',
    614: 'Centaurs Helmet',
    615: 'Minotaurs Horns',
    616: 'Necromancers Hat',
    617: 'Necromancers Boots',
    618: 'Silver Precision Ring',
    619: 'Gold Precision Ring',
    620: 'Diamond Precision Ring',
    621: 'Silver Arcane Ring',
    622: 'Gold Arcane Ring',
    623: 'Diamond Arcane Ring',
    624: 'Silver Brute Bracelet',
    625: 'Gold Brute Bracelet',
    626: 'Diamond Brute Bracelet',
    627: 'Silver Marksman Bracelet',
    628: 'Gold Marksman Bracelet',
    629: 'Diamond Marksman Bracelet',
    630: 'Silver Precision Ring Enchanted',
    631: 'Gold Precision Ring Enchanted',
    632: 'Diamond Precision Ring Enchanted',
    633: 'Silver Arcane Ring Enchanted',
    634: 'Gold Arcane Ring Enchanted',
    635: 'Diamond Arcane Ring Enchanted',
    636: 'Silver Brute Bracelet Enchanted',
    637: 'Gold Brute Bracelet Enchanted',
    638: 'Diamond Brute Bracelet Enchanted',
    639: 'Silver Marksman Bracelet Enchanted',
    640: 'Gold Marksman Bracelet Enchanted',
    641: 'Diamond Marksman Bracelet Enchanted',
    642: 'Silver Precision Symbol',
    643: 'Gold Precision Symbol',
    644: 'Diamond Precision Symbol',
    645: 'Silver Arcane Symbol',
    646: 'Gold Arcane Symbol',
    647: 'Diamond Arcane Symbol',
    648: 'Silver Brute Symbol',
    649: 'Gold Brute Symbol',
    650: 'Diamond Brute Symbol',
    651: 'Silver Marksman Symbol',
    652: 'Gold Marksman Symbol',
    653: 'Diamond Marksman Symbol',
    654: 'Silver Berserker Symbol',
    655: 'Gold Berserker Symbol',
    656: 'Diamond Berserker Symbol',
    657: 'Silver Sorcerer Symbol',
    658: 'Gold Sorcerer Symbol',
    659: 'Diamond Sorcerer Symbol',
    660: 'Silver Berserker Ring',
    661: 'Silver Berserker Ring Enchanted',
    662: 'Gold Berserker Ring',
    663: 'Gold Berserker Ring Enchanted',
    664: 'Diamond Berserker Ring',
    665: 'Diamond Berserker Ring Enchanted',
    666: 'Silver Sorcerer Bracelet',
    667: 'Gold Sorcerer Bracelet',
    668: 'Diamond Sorcerer Bracelet',
    669: 'Silver Sorcerer Bracelet Enchanted',
    670: 'Gold Sorcerer Bracelet Enchanted',
    671: 'Diamond Sorcerer Bracelet Enchanted',
    672: 'Treasure Hunter Gloves',
    673: 'Warriors Platebody',
    674: 'Artisans Boots',
    675: 'Granite Shield',
    676: 'Chefs Hat',
    677: 'Dragonscale Shield',
    678: 'Dragonscale Boots',
    679: 'Halloween Candy',
    680: 'Christmas Present',
    681: 'Valentines Flower',
    682: 'Birthday Balloon',
    683: 'Auto Loadout Token',
    684: 'Clan Vault Space Token',
    685: 'Boss Page Piece Mountain',
    686: 'Boss Page Piece Burning',
    687: 'Boss Page Piece Underworld',
    688: 'Boss Page Piece Godly',
    689: 'Boss Page Piece Stone',
    690: 'Boss Page Piece Mutated',
    691: 'Kronos Scroll',
    692: 'Book Of The Sage Cook',
    693: 'Book Of Skinning Techniques',
    694: 'Fishermans Lost Page',
    695: 'Lumberjacks Lost Page',
    696: 'Arrow Crafting Secrets',
    697: 'Textile Manufacturing Techniques',
    698: 'Book Of Potions',
    699: 'Negotiation Techniques',
    700: 'Otherworldly Gloves',
    701: 'Otherworldly Boots',
    702: 'Enhanced Redwood Arrow',
    703: 'Enhanced Magical Arrow',
    704: 'Melee Resistance Seed Tier 1',
    705: 'Melee Resistance Seed Tier 2',
    706: 'Melee Resistance Seed Tier 3',
    707: 'Melee Resistance Seed Tier 4',
    708: 'Archery Resistance Seed Tier 1',
    709: 'Archery Resistance Seed Tier 2',
    710: 'Archery Resistance Seed Tier 3',
    711: 'Archery Resistance Seed Tier 4',
    712: 'Magic Resistance Seed Tier 1',
    713: 'Magic Resistance Seed Tier 2',
    714: 'Magic Resistance Seed Tier 3',
    715: 'Magic Resistance Seed Tier 4',
    716: 'Melee Resistance Herb Tier 1',
    717: 'Melee Resistance Herb Tier 2',
    718: 'Melee Resistance Herb Tier 3',
    719: 'Melee Resistance Herb Tier 4',
    720: 'Archery Resistance Herb Tier 1',
    721: 'Archery Resistance Herb Tier 2',
    722: 'Archery Resistance Herb Tier 3',
    723: 'Archery Resistance Herb Tier 4',
    724: 'Magic Resistance Herb Tier 1',
    725: 'Magic Resistance Herb Tier 2',
    726: 'Magic Resistance Herb Tier 3',
    727: 'Magic Resistance Herb Tier 4',
    728: 'Melee Resistance Potion Tier 1',
    729: 'Melee Resistance Potion Tier 2',
    730: 'Melee Resistance Potion Tier 3',
    731: 'Melee Resistance Potion Tier 4',
    732: 'Archery Resistance Potion Tier 1',
    733: 'Archery Resistance Potion Tier 2',
    734: 'Archery Resistance Potion Tier 3',
    735: 'Archery Resistance Potion Tier 4',
    736: 'Magic Resistance Potion Tier 1',
    737: 'Magic Resistance Potion Tier 2',
    738: 'Magic Resistance Potion Tier 3',
    739: 'Magic Resistance Potion Tier 4',
    740: 'Guardians Lamp',
    741: 'Guardians Brewspoon',
    742: 'Guardians Trowel',
    743: 'Guardians Mallet',
    744: 'Guardians Chisel',
    745: 'Citadel Woodworking Tips',
    746: 'Grouping Techniques',
    747: 'Pet Woodcutting',
    748: 'Pet Fishing',
    749: 'Pet Mining',
    750: 'Pet Cooking',
    751: 'Pet Smithing',
    752: 'Pet Carpentry',
    753: 'Pet Foraging',
    754: 'Pet Farming',
    755: 'Pet Agility',
    756: 'Pet Plundering',
    757: 'Pet Enchanting',
    758: 'Pet Brewing',
    759: 'Pet Crafting',
    760: 'Pet Attack',
    761: 'Pet Strength',
    762: 'Pet Defence',
    763: 'Pet Archer Tier 1',
    764: 'Pet Magic Tier 1',
    765: 'Questing Token',
    766: 'Gilded Pet 1',
    767: 'Gilded Pet 2',
    768: 'Pet Melee Tier 1',
    769: 'Pet Melee Tier 2',
    770: 'Pet Melee Tier 3',
    771: 'Pet Melee Tier 4',
    772: 'Pet Melee Tier 5',
    773: 'Pet Melee Tier 6',
    774: 'Pet Melee Tier 7',
    775: 'Pet Archer Tier 2',
    776: 'Pet Archer Tier 3',
    777: 'Pet Archer Tier 4',
    778: 'Pet Archer Tier 5',
    779: 'Pet Archer Tier 6',
    780: 'Pet Archer Tier 7',
    781: 'Pet Magic Tier 2',
    782: 'Pet Magic Tier 3',
    783: 'Pet Magic Tier 4',
    784: 'Pet Magic Tier 5',
    785: 'Pet Magic Tier 6',
    786: 'Pet Magic Tier 7',
    787: 'Otherworldly Gemstone',
    788: 'Pet Melee Tier 8',
    789: 'Pet Archer Tier 8',
    790: 'Pet Magic Tier 8',
    791: 'Otherworldly Scimitar',
    792: 'Otherworldly Battle Axe',
    793: 'Otherworldly Bow',
    794: 'Otherworldly Club',
    795: 'Otherworldly Crossbow',
    796: 'Otherworldly Heavy Hammer',
    797: 'Otherworldly Longsword',
    798: 'Otherworldly Spear',
    799: 'Otherworldly Staff',
    800: 'Otherworldly Hatchet',
    801: 'Otherworldly Pickaxe',
    802: 'Otherworldly Fishing Rod',
    803: 'Otherworldly Rake',
    804: 'Otherworldly Secateurs',
    805: 'Otherworldly Hammer',
    806: 'Otherworldly Saw',
    807: 'Otherworldly Cooking Pan',
    808: 'Otherworldly Crafting Needle',
    809: 'Otherworldly Philosopher Stone',
    810: 'Otherworldly Lockpicks',
    811: 'Otherworldly Jumping Rope',
    812: 'Warriors Platelegs',
    813: 'Spiked Shield',
    814: 'Quiver',
    815: 'Spider Fang',
    816: 'Ancient Bone',
    817: 'Golem Fragment',
    818: 'Otherworldly Essence',
    819: 'Common Thread',
    820: 'Rare Thread',
    821: 'Common Smoke Bomb',
    822: 'Rare Smoke Bomb',
    823: 'Common Seasoning',
    824: 'Rare Seasoning',
    825: 'Common Wax',
    826: 'Rare Wax',
    827: 'Exterminating Token',
    828: 'Common Clay Core',
    829: 'Rare Clay Core',
    830: 'Common Prehistoric Elixir',
    831: 'Rare Prehistoric Elixir',
    832: 'Basilisk Scale',
    833: 'Basilisk Scale Trousers',
    834: 'Basilisk Scale Coat',
    835: 'Stone Boots',
    836: 'Rocs Talon',
    837: 'Dire Wolf Fang',
    838: 'Behemoth Hide Boots',
    839: 'Ancient Boots',
    840: 'Drake Hide Hat',
    841: 'Nagas Crown',
    842: 'Abyssal Maul',
    843: 'Furys Glaive',
    844: 'Scorched Halberd',
    845: 'Ghostly Hood',
    846: 'Ghostly Top',
    847: 'Ghostly Pants',
    848: 'Feather Hat',
    849: 'Feather Jacket',
    850: 'Feather Pants',
    851: 'Wolf Fur Hat',
    852: 'Wolf Fur Jacket',
    853: 'Wolf Fur Pants',
    854: 'Crafting Ticket',
    855: 'Plundering Ticket',
    856: 'Woodcutting Ticket',
    857: 'Fishing Ticket',
    858: 'Mining Ticket',
    859: 'Smithing Ticket',
    860: 'Cooking Ticket',
    861: 'Enchanting Ticket',
    862: 'Foraging Ticket',
    863: 'Farming Ticket',
    864: 'Brewing Ticket',
    865: 'Carpentry Ticket',
    866: 'Agility Ticket',
    867: 'Exterminating Ticket',
    868: 'Crafting Gloves',
    869: 'Woodcutting Gloves',
    870: 'Carpentry Gloves',
    871: 'Fishing Gloves',
    872: 'Cooking Gloves',
    873: 'Mining Gloves',
    874: 'Smithing Gloves',
    875: 'Foraging Gloves',
    876: 'Farming Gloves',
    877: 'Agility Gloves',
    878: 'Plundering Gloves',
    879: 'Enchanting Gloves',
    880: 'Brewing Gloves',
    881: 'Bloodmoon Bag',
    882: 'Bloodmoon Belt',
    883: 'Lunar Belt',
    884: 'Bloodmoon Secrets',
    885: 'Lil Eclipse',
    886: 'Bloodmoon Worm',
    887: 'Bloodmoon Eel',
    888: 'Cooked Bloodmoon Eel',
    889: 'Bloodmoon Helmet',
    890: 'Bloodmoon Bait Jar',
    891: 'Bloodmoon Gem',
    '-1': 'None Equipped',
};

// Function to get item name by ID
export function getItemName(id: number | string | null): string | null {
    if (id === null || id === undefined) return null;
    const numericId = typeof id === 'string' ? parseInt(id, 10) : id;
    return items[numericId] || null;
}

export default items;
