import { SkillItem } from '@/types/calculator.types';

export const MINING_ITEMS: SkillItem[] = [
    {
        name: 'Copper',
        level: 1,
        exp: 7.5,
        seconds: 3,
        expPerSecond: 2.5,
        goldValue: 5,
        goldPerSecond: 1.7,
    },
    {
        name: 'Tin',
        level: 1,
        exp: 7.5,
        seconds: 3,
        expPerSecond: 2.5,
        goldValue: 5,
        goldPerSecond: 1.7,
    },
    {
        name: 'Iron',
        level: 15,
        exp: 12,
        seconds: 4.5,
        expPerSecond: 2.67,
        goldValue: 8,
        goldPerSecond: 1.8,
    },
    {
        name: 'Silver',
        level: 25,
        exp: 18.5,
        seconds: 6,
        expPerSecond: 3.08,
        goldValue: 15,
        goldPerSecond: 2.5,
    },
    {
        name: 'Coal',
        level: 30,
        exp: 24,
        seconds: 7.5,
        expPerSecond: 3.2,
        goldValue: 11,
        goldPerSecond: 1.5,
    },
    {
        name: 'Gold',
        level: 45,
        exp: 75,
        seconds: 21,
        expPerSecond: 3.57,
        goldValue: 52,
        goldPerSecond: 2.5,
    },
    {
        name: 'Platinum',
        level: 55,
        exp: 78,
        seconds: 18,
        expPerSecond: 4.33,
        goldValue: 62,
        goldPerSecond: 3.4,
    },
    {
        name: 'Meteorite',
        level: 70,
        exp: 125,
        seconds: 26,
        expPerSecond: 4.81,
        goldValue: 105,
        goldPerSecond: 4.0,
    },
    {
        name: 'Diamond',
        level: 75,
        exp: 148,
        seconds: 29.5,
        expPerSecond: 5.02,
        goldValue: 125,
        goldPerSecond: 4.2,
    },
    {
        name: 'Titanium',
        level: 85,
        exp: 180,
        seconds: 35,
        expPerSecond: 5.14,
        goldValue: 155,
        goldPerSecond: 4.4,
    },
];
