export const UPGRADE_CATEGORIES = {
  general: [
    "keepItSpacious",
    "valuedClanMember",
    "housing",
    "lazyRaider",
    "extraLoadouts",
    "offlineProgress",
    "toolbeltUpgrade",
  ],
  skilling: [
    "ancientWisdom",
    "masterCrafter",
    "mostEfficientFisherman",
    "farmingTrickery",
    "theFisherman",
    "powerForager",
    "plankBargain",
    "smeltingMagic",
    "theLumberjack",
  ],
  combat: [
    "autoEating",
    "autoLooting",
    "bossSlayer",
    "ninja",
    "monsterHunter",
    "showUsTheMoney",
    "kronosWho?",
    "pickyEater",
    "ammo-saver",
    "teamwork",
    "bountyHunter",
  ],
  unlockedWithItems: [
    "arrowCrafter",
    "keepItBurning",
    "betterSkinner",
    "delicateManufacturing",
    "gettingInSync",
    "lastNegotiation",
    "prestigiousWoodworking",
    "responsibleDrinking",
    "betterFisherman",
    "betterLumberjack",
  ],
};
